name: ci-test

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test Tsc
    runs-on: ubuntu-latest

    steps:

      - name: Use Checkout
        uses: actions/checkout@v2
      
      - name: Use NodeJS
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm',
          cache-dependency-path: '**/package-lock.json'

      # - name: Use Cache
      #   uses: actions/cache@v2
      #   id: cache
      #   with:
      #     path: '**/node_modules'
      #     key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - run: npm run tsc
      - run: npm run test