name: ci-test

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test Tsc
    runs-on: ubuntu-latest

    steps:

      - name: Use Checkout
        uses: actions/checkout@v2
      
      - name: Use NodeJS
        uses: actions/setup-node@v2
        id: cache
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Dependencies If Cache Miss
        if: steps.cache.outputs.cache-hit == 'true' 
        run: npm ci

      - run: ls -al
      - run: ls -al ~/
      - run: ls -al ~/.npm
      - run: npx jest --clearCache
      - run: npm run tsc
      - run: npm run test